/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liveray.client.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Cliente service. Represents a row in the &quot;client&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liveray.client.service.model.impl.ClienteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liveray.client.service.model.impl.ClienteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cliente
 * @generated
 */
@ProviderType
public interface ClienteModel extends BaseModel<Cliente> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cliente model instance should use the {@link Cliente} interface instead.
	 */

	/**
	 * Returns the primary key of this cliente.
	 *
	 * @return the primary key of this cliente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cliente.
	 *
	 * @param primaryKey the primary key of this cliente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cliente ID of this cliente.
	 *
	 * @return the cliente ID of this cliente
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this cliente.
	 *
	 * @param clienteId the cliente ID of this cliente
	 */
	public void setClienteId(long clienteId);

	/**
	 * Returns the plano ID of this cliente.
	 *
	 * @return the plano ID of this cliente
	 */
	public long getPlanoId();

	/**
	 * Sets the plano ID of this cliente.
	 *
	 * @param planoId the plano ID of this cliente
	 */
	public void setPlanoId(long planoId);

	/**
	 * Returns the nome of this cliente.
	 *
	 * @return the nome of this cliente
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this cliente.
	 *
	 * @param nome the nome of this cliente
	 */
	public void setNome(String nome);

	/**
	 * Returns the rg of this cliente.
	 *
	 * @return the rg of this cliente
	 */
	@AutoEscape
	public String getRg();

	/**
	 * Sets the rg of this cliente.
	 *
	 * @param rg the rg of this cliente
	 */
	public void setRg(String rg);

	/**
	 * Returns the nome mae of this cliente.
	 *
	 * @return the nome mae of this cliente
	 */
	@AutoEscape
	public String getNomeMae();

	/**
	 * Sets the nome mae of this cliente.
	 *
	 * @param nomeMae the nome mae of this cliente
	 */
	public void setNomeMae(String nomeMae);

	/**
	 * Returns the nome pai of this cliente.
	 *
	 * @return the nome pai of this cliente
	 */
	@AutoEscape
	public String getNomePai();

	/**
	 * Sets the nome pai of this cliente.
	 *
	 * @param nomePai the nome pai of this cliente
	 */
	public void setNomePai(String nomePai);

	/**
	 * Returns the orgao expedidor of this cliente.
	 *
	 * @return the orgao expedidor of this cliente
	 */
	@AutoEscape
	public String getOrgaoExpedidor();

	/**
	 * Sets the orgao expedidor of this cliente.
	 *
	 * @param orgaoExpedidor the orgao expedidor of this cliente
	 */
	public void setOrgaoExpedidor(String orgaoExpedidor);

	/**
	 * Returns the estado of this cliente.
	 *
	 * @return the estado of this cliente
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this cliente.
	 *
	 * @param estado the estado of this cliente
	 */
	public void setEstado(String estado);

	/**
	 * Returns the data expedicao of this cliente.
	 *
	 * @return the data expedicao of this cliente
	 */
	public Date getDataExpedicao();

	/**
	 * Sets the data expedicao of this cliente.
	 *
	 * @param dataExpedicao the data expedicao of this cliente
	 */
	public void setDataExpedicao(Date dataExpedicao);

}